Repository lnbits/lnbits, pull requests merged in 2022-10, with the labels that each got.

#1022 Add MYNODE Image
  lnbits/core/templates/core/index.html
  lnbits/static/images/mynode.png
  lnbits/static/images/mynodel.png
Labels: deployment

#1007 Remove unused proxy_fix
  lnbits/app.py
  lnbits/proxy_fix.py
Labels: code health

#914 Allow more than 2-nd level domain in incoming ln-addresses
  lnbits/core/views/api.py
Labels: enhancement, extension

#873 fix mypy for extensions
  lnbits/extensions/copilot/crud.py
  lnbits/extensions/copilot/tasks.py
  lnbits/extensions/copilot/views.py
  lnbits/extensions/copilot/views_api.py
  lnbits/extensions/discordbot/crud.py
  lnbits/extensions/discordbot/views.py
  lnbits/extensions/discordbot/views_api.py
  lnbits/extensions/example/views.py
  lnbits/extensions/subdomains/crud.py
  lnbits/extensions/subdomains/models.py
  lnbits/extensions/subdomains/tasks.py
  lnbits/extensions/subdomains/views.py
  lnbits/extensions/subdomains/views_api.py
  pyproject.toml
Labels: code health

#1084 LNURLw extension: refactor try except block
  lnbits/extensions/withdraw/lnurl.py
Labels: bug, extension
