Repository lnbits/lnbits, pull requests merged in 2022-09, with the labels that each got.

#951 reuse db connection for pending and expired tasks
  lnbits/extensions/boltcards/crud.py
  lnbits/extensions/boltcards/lnurl.py
  lnbits/tasks.py
Labels: enhancement, core

#912 Updates and fixes
  .env.example
  poetry.lock
  pyproject.toml
Labels: bug, code health

#1023 add small description in UI
  lnbits/extensions/scrub/templates/scrub/index.html
Labels: documentation, extension

#1021 downgrade pyln from 0.12.0 to 0.11.1
  poetry.lock
  pyproject.toml
Labels: dependencies
