Repository lnbits/lnbits, pull requests merged in 2022-07, with the labels that each got.

#711 Testing: postgres db backend
  .github/workflows/tests.yml
  Makefile
  docs/devs/development.md
  lnbits/core/crud.py
  lnbits/core/views/api.py
  tests/conftest.py
  tests/core/views/test_api.py
  tests/core/views/test_generic.py
  tests/core/views/test_public_api.py
  tests/extensions/bleskomat/conftest.py
  tests/extensions/bleskomat/test_lnurl_api.py
  tests/mocks.py
Labels: bug, testing

#718 Spark: increase timeout and improved error handling
  lnbits/wallets/spark.py
Labels: bug, wallets

#738 CI: regtest with `LndRestWallet` and `CLightningWallet`
  .github/workflows/regtest.yml
  Makefile
  tests/mocks.py
Labels: wallets, testing

#743 `make format` everything
  .github/workflows/formatting.yml
  lnbits/__main__.py
  lnbits/bolt11.py
  lnbits/commands.py
  lnbits/core/crud.py
  lnbits/core/models.py
  lnbits/core/services.py
  lnbits/core/tasks.py
  lnbits/core/views/api.py
  lnbits/core/views/generic.py
  lnbits/core/views/public_api.py
  lnbits/db.py
  lnbits/decorators.py
  lnbits/extensions/bleskomat/exchange_rates.py
  lnbits/extensions/bleskomat/lnurl_api.py
  lnbits/extensions/bleskomat/models.py
  lnbits/extensions/bleskomat/views_api.py
  lnbits/extensions/copilot/models.py
  lnbits/extensions/discordbot/models.py
  lnbits/extensions/jukebox/models.py
  lnbits/extensions/livestream/views.py
  lnbits/extensions/lnaddress/lnurl.py
  lnbits/extensions/lndhub/decorators.py
  lnbits/extensions/lndhub/views.py
  lnbits/extensions/lndhub/views_api.py
  lnbits/extensions/lnticket/crud.py
  lnbits/extensions/lnticket/models.py
  lnbits/extensions/lnurldevice/lnurl.py
  lnbits/extensions/lnurlp/crud.py
  lnbits/extensions/lnurlp/models.py
  lnbits/extensions/lnurlpayout/__init__.py
  lnbits/extensions/lnurlpayout/crud.py
  lnbits/extensions/lnurlpayout/tasks.py
  lnbits/extensions/offlineshop/crud.py
  lnbits/extensions/offlineshop/helpers.py
  lnbits/extensions/offlineshop/models.py
  lnbits/extensions/offlineshop/views.py
  lnbits/extensions/subdomains/cloudflare.py
  lnbits/extensions/tpos/__init__.py
  lnbits/extensions/tpos/views.py
  lnbits/extensions/tpos/views_api.py
  lnbits/extensions/usermanager/models.py
  lnbits/extensions/withdraw/lnurl.py
  lnbits/proxy_fix.py
  lnbits/tasks.py
  lnbits/utils/exchange_rates.py
  lnbits/wallets/base.py
  lnbits/wallets/clightning.py
  lnbits/wallets/eclair.py
  lnbits/wallets/fake.py
  lnbits/wallets/lnbits.py
  lnbits/wallets/lnd_grpc_files/lightning_pb2.py
  lnbits/wallets/lndgrpc.py
  lnbits/wallets/lndrest.py
  lnbits/wallets/lnpay.py
  lnbits/wallets/lntxbot.py
  lnbits/wallets/macaroon/__init__.py
  lnbits/wallets/macaroon/macaroon.py
  lnbits/wallets/opennode.py
  lnbits/wallets/spark.py
Labels: code health

#719 CI: Migration SQLite to PostgreSQL
  .dockerignore
  .github/workflows/migrations.yml
  docs/guide/installation.md
  lnbits/extensions/lnurldevice/migrations.py
  lnbits/extensions/lnurldevice/templates/lnurldevice/_api_docs.html
  tools/conv.py
Labels: testing

#748 Repo: Clean up and remove old files (attempt 2)
  .editorconfig
  Procfile
  app.json
Labels: code health

#646 Core: add internal flag for invoice creation to use FakeWallet
  lnbits/core/services.py
  lnbits/core/templates/core/_api_docs.html
  lnbits/core/views/api.py
  lnbits/settings.py
  lnbits/wallets/fake.py
  tests/core/views/test_api.py
Labels: enhancement, core

#730 error in `/usermanager/api/v1/extensions`
  lnbits/extensions/usermanager/views_api.py
Labels: bug, extension, api

#751 Fix loguru warnings
  lnbits/core/services.py
  lnbits/core/views/api.py
  lnbits/utils/exchange_rates.py
Labels: bug

#750 `FakeWallet`: do not mark payments as failed
  lnbits/wallets/fake.py
Labels: bug, wallets

#768 Docs: add mkcert instructions
  docs/guide/installation.md
Labels: documentation

#713 Fix/tpos tips #697
  lnbits/extensions/tpos/crud.py
  lnbits/extensions/tpos/models.py
  lnbits/extensions/tpos/tasks.py
  lnbits/extensions/tpos/templates/tpos/index.html
  lnbits/extensions/tpos/templates/tpos/tpos.html
  lnbits/extensions/tpos/views_api.py
Labels: bug, frontend

#704 Add voucher design
  lnbits/extensions/withdraw/README.md
  lnbits/extensions/withdraw/crud.py
  lnbits/extensions/withdraw/migrations.py
  lnbits/extensions/withdraw/models.py
  lnbits/extensions/withdraw/static/js/index.js
  lnbits/extensions/withdraw/templates/withdraw/index.html
  lnbits/extensions/withdraw/templates/withdraw/print_qr_custom.html
  lnbits/extensions/withdraw/views.py
  lnbits/static/images/default_voucher.png
  lnbits/static/images/voucher_template.svg
Labels: extension, themes

#779 .gitignore coverage.xml + do not delete mock_data.zip
  .gitignore
  Makefile
Labels: testing, code health

#758 LNURLp: check description hash
  lnbits/core/views/api.py
Labels: extension

#721 Add Nix and Poetry to the project
  .gitignore
  build.py
  flake.lock
  flake.nix
  lnbits/__main__.py
  lnbits/app.py
  lnbits/extensions/bleskomat/__init__.py
  lnbits/extensions/copilot/__init__.py
  lnbits/extensions/discordbot/__init__.py
  lnbits/extensions/jukebox/__init__.py
  lnbits/extensions/livestream/__init__.py
  lnbits/extensions/lnurlp/__init__.py
  lnbits/extensions/offlineshop/__init__.py
  lnbits/extensions/splitpayments/__init__.py
  lnbits/extensions/withdraw/__init__.py
  lnbits/server.py
  nix/modules/lnbits-service.nix
  nix/tests/default.nix
  nix/tests/nixos-module/default.nix
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: deployment

#760 WIP: Enable `mypy` linting of the entire code base
  .github/workflows/mypy.yml
  Pipfile
  Pipfile.lock
  lnbits/app.py
  lnbits/core/crud.py
  lnbits/core/models.py
  lnbits/core/services.py
  lnbits/core/tasks.py
  lnbits/core/views/api.py
  lnbits/core/views/generic.py
  lnbits/decorators.py
  lnbits/extensions/events/views_api.py
  lnbits/extensions/lnurlpayout/templates/lnurlpayout/_api_docs.html
  lnbits/helpers.py
  lnbits/tasks.py
  lnbits/utils/exchange_rates.py
  lnbits/wallets/eclair.py
  lnbits/wallets/fake.py
  lnbits/wallets/lnpay.py
  lnbits/wallets/macaroon/macaroon.py
  lnbits/wallets/opennode.py
  mypy.ini
  result
  tests/core/views/test_api.py
Labels: code health

#596 Adds generic QR maker endpoint, url can be embedded
  lnbits/core/views/api.py
Labels: core, api

#699 onchain watch-only extension - phase 2
  lnbits/extensions/satspay/templates/satspay/index.html
  lnbits/extensions/streamalerts/README.md
  lnbits/extensions/streamalerts/templates/streamalerts/index.html
  lnbits/extensions/watchonly/README.md
  lnbits/extensions/watchonly/__init__.py
  lnbits/extensions/watchonly/config.json
  lnbits/extensions/watchonly/crud.py
  lnbits/extensions/watchonly/helpers.py
  lnbits/extensions/watchonly/migrations.py
  lnbits/extensions/watchonly/models.py
  lnbits/extensions/watchonly/static/js/index.js
  lnbits/extensions/watchonly/static/js/map.js
  lnbits/extensions/watchonly/static/js/tables.js
  lnbits/extensions/watchonly/static/js/utils.js
  lnbits/extensions/watchonly/templates/watchonly/_api_docs.html
  lnbits/extensions/watchonly/templates/watchonly/index.html
  lnbits/extensions/watchonly/views_api.py
  lnbits/static/js/base.js
  tools/conv.py
Labels: enhancement, extension

#677 SCRUB extension
  lnbits/extensions/scrub/README.md
  lnbits/extensions/scrub/__init__.py
  lnbits/extensions/scrub/config.json
  lnbits/extensions/scrub/crud.py
  lnbits/extensions/scrub/migrations.py
  lnbits/extensions/scrub/models.py
  lnbits/extensions/scrub/static/js/index.js
  lnbits/extensions/scrub/tasks.py
  lnbits/extensions/scrub/templates/scrub/_api_docs.html
  lnbits/extensions/scrub/templates/scrub/_lnurl.html
  lnbits/extensions/scrub/templates/scrub/index.html
  lnbits/extensions/scrub/views.py
  lnbits/extensions/scrub/views_api.py
  tests/data/mock_data.zip
  tools/conv.py
Labels: extension proposal

#728 `satspay` extension improvements
  lnbits/extensions/satspay/__init__.py
  lnbits/extensions/satspay/crud.py
  lnbits/extensions/satspay/models.py
  lnbits/extensions/satspay/static/js/utils.js
  lnbits/extensions/satspay/templates/satspay/_api_docs.html
  lnbits/extensions/satspay/templates/satspay/display.html
  lnbits/extensions/satspay/templates/satspay/index.html
  lnbits/extensions/satspay/views.py
  lnbits/extensions/satspay/views_api.py
  lnbits/extensions/watchonly/crud.py
  lnbits/extensions/watchonly/static/js/index.js
  lnbits/extensions/watchonly/templates/watchonly/index.html
  lnbits/extensions/watchonly/views_api.py
Labels: enhancement, extension

#816 CI: add coverage report for regtest tests
  .github/workflows/regtest.yml
Labels: testing
