Repository lnbits/lnbits, pull requests merged in 2022-06, with the labels that each got.

#610 LNURLw webhook_url
  lnbits/extensions/withdraw/crud.py
  lnbits/extensions/withdraw/lnurl.py
  lnbits/extensions/withdraw/migrations.py
  lnbits/extensions/withdraw/models.py
  lnbits/extensions/withdraw/static/js/index.js
  lnbits/extensions/withdraw/templates/withdraw/_api_docs.html
  lnbits/extensions/withdraw/templates/withdraw/index.html
Labels: enhancement, extension

#641 Added maxfee parameter to Spark pay method
  lnbits/wallets/spark.py
Labels: wallets

#649 Core: fix internal webhooks
  lnbits/core/crud.py
  lnbits/tasks.py
Labels: bug, core

#642 Allow for custom image logo
  .env.example
  lnbits/helpers.py
  lnbits/settings.py
  lnbits/templates/base.html
  lnbits/templates/public.html
Labels: themes

#663 lnurlp: support for floating point fiat values
  lnbits/extensions/lnurlp/crud.py
  lnbits/extensions/lnurlp/lnurl.py
  lnbits/extensions/lnurlp/migrations.py
  lnbits/extensions/lnurlp/models.py
  lnbits/extensions/lnurlp/views_api.py
Labels: bug, extension

#632 Fix GET transactions endpoint in usermanager docs
  lnbits/extensions/usermanager/templates/usermanager/_api_docs.html
Labels: documentation

#667 Fix HTML response to non browser request
  lnbits/app.py
Labels: api

#671 Hotfix for JSON response
  lnbits/app.py
Labels: bug

#648 Code cleanup: black formatting
  conv.py
  lnbits/bolt11.py
  lnbits/core/views/api.py
  lnbits/core/views/generic.py
  lnbits/decorators.py
  lnbits/extensions/discordbot/models.py
  lnbits/extensions/discordbot/views_api.py
  lnbits/extensions/example/__init__.py
  lnbits/extensions/example/models.py
  lnbits/extensions/example/views_api.py
  lnbits/extensions/jukebox/crud.py
  lnbits/extensions/jukebox/views_api.py
  lnbits/extensions/livestream/views.py
  lnbits/extensions/offlineshop/helpers.py
  lnbits/extensions/paywall/views_api.py
  lnbits/extensions/streamalerts/views_api.py
  lnbits/extensions/withdraw/lnurl.py
  lnbits/extensions/withdraw/views.py
  lnbits/extensions/withdraw/views_api.py
  lnbits/helpers.py
  lnbits/settings.py
  lnbits/wallets/eclair.py
  lnbits/wallets/macaroon/__init__.py
  lnbits/wallets/macaroon/macaroon.py
  tests/conftest.py
  tests/core/views/test_generic.py
  tests/extensions/bleskomat/conftest.py
  tests/helpers.py
Labels: code health

#594 /api/v1/payments with limit and offset
  lnbits/core/views/api.py
Labels: core, api

#531 Delete expired invoices after one pending check
  lnbits/tasks.py
Labels: core

#566 WIP: More automated tests
  .github/workflows/mypy.yml
  .github/workflows/tests.yml
  Makefile
  lnbits/core/views/api.py
  tests/conftest.py
  tests/core/views/test_api.py
  tests/core/views/test_public_api.py
  tests/helpers.py
  tests/mocks.py
Labels: testing
