Repository lnbits/lnbits, pull requests merged in 2023-06, with the labels that each got.

#1742 bump to version 0.10.9
  pyproject.toml
Labels: deployment

#1748 Ability to limit available fiat currencies
  .env.example
  lnbits/core/templates/admin/_tab_server.html
  lnbits/core/views/api.py
  lnbits/core/views/generic.py
  lnbits/settings.py
Labels: enhancement

#1784 Wallets: lntips no timeout for the sse connection
  lnbits/wallets/lntips.py
Labels: bug, wallets

#1785 Add pre-commit-config to gitignore
  .gitignore
Labels: code health

#1783 ignore upgrades dir in linters and formatters and precommit
  .pre-commit-config.yaml
  .prettierignore
  pyproject.toml
Labels: code health
