Repository lnbits/lnbits, pull requests merged in 2023-08, with the labels that each got.

#1845 UI: paste payment request from clipboard
  lnbits/core/static/js/service-worker.js
  lnbits/core/static/js/wallet.js
  lnbits/core/templates/core/wallet.html
  lnbits/static/bundle.min.js
  lnbits/static/i18n/en.js
Labels: enhancement, frontend

#1781 [REFACTOR] payments sse endpoint
  lnbits/app.py
  lnbits/core/models.py
  lnbits/core/views/api.py
  lnbits/middleware.py
Labels: enhancement, code health

#1782 Update payments on invoice creation
  lnbits/core/static/js/wallet.js
  lnbits/core/templates/core/wallet.html
Labels: code health
