Repository lnbits/lnbits, pull requests merged in 2023-07, with the labels that each got.

#1825 Increase default invoice expiry to 1 hour
  .env.example
  lnbits/settings.py
Labels: code health

#1551 add github workflow for checking openapi
  .github/workflows/openapi.yml
  Makefile
  lnbits/settings.py
  poetry.lock
  pyproject.toml
Labels: bug, enhancement, code health

#1832 follow redirect for lnurls
  lnbits/core/views/api.py
Labels: bug

#1839 Tests: hold invoice tests pending during payment
  lnbits/wallets/lnbits.py
  tests/core/views/test_api.py
Labels: enhancement, testing, lightning, node
