Repository lnbits/lnbits, pull requests merged in 2023-09, with the labels that each got.

#1393 [FEAT] Push notification integration into core
  lnbits/app.py
  lnbits/core/crud.py
  lnbits/core/migrations.py
  lnbits/core/models.py
  lnbits/core/services.py
  lnbits/core/static/js/service-worker.js
  lnbits/core/tasks.py
  lnbits/core/views/admin_api.py
  lnbits/core/views/api.py
  lnbits/core/views/generic.py
  lnbits/helpers.py
  lnbits/settings.py
  lnbits/static/js/components.js
  lnbits/tasks.py
  lnbits/templates/base.html
  poetry.lock
  pyproject.toml
Labels: core, feature request

#1918 make wallets name prettier!
  lnbits/core/templates/admin/_tab_funding.html
  lnbits/core/templates/admin/index.html
Labels: frontend, feature request

#1940 Support custom path for installed extensions
  .env.example
  lnbits/app.py
  lnbits/extension_manager.py
  lnbits/helpers.py
  lnbits/server.py
  lnbits/settings.py
Labels: enhancement

#1965 Add Markdown capability globally
  lnbits/core/static/js/index.js
  lnbits/core/static/js/service-worker.js
  lnbits/core/templates/admin/_tab_theme.html
  lnbits/core/templates/core/index.html
  lnbits/static/bundle.min.js
  lnbits/static/js/base.js
  lnbits/static/vendor.json
  lnbits/static/vendor/showdown.js
  lnbits/templates/base.html
  package-lock.json
  package.json
Labels: enhancement, feature request
