Repository lnbits/lnbits, pull requests merged in 2023-11, with the labels that each got.

#2096 hotfix toolbar title
  lnbits/templates/base.html
Labels: bug

#2086 feat: add getalby wallet as funding source
  .env.example
  README.md
  docs/guide/faq.md
  docs/guide/wallets.md
  lnbits/settings.py
  lnbits/static/bundle.min.js
  lnbits/static/i18n/br.js
  lnbits/static/i18n/cn.js
  lnbits/static/i18n/cs.js
  lnbits/static/i18n/de.js
  lnbits/static/i18n/en.js
  lnbits/static/i18n/es.js
  lnbits/static/i18n/fr.js
  lnbits/static/i18n/it.js
  lnbits/static/i18n/jp.js
  lnbits/static/i18n/nl.js
  lnbits/static/i18n/pi.js
  lnbits/static/i18n/pl.js
  lnbits/static/i18n/pt.js
  lnbits/static/i18n/sk.js
  lnbits/static/i18n/we.js
  lnbits/static/js/components/lnbits-funding-sources.js
  lnbits/static/js/service-worker.js
  lnbits/wallets/__init__.py
  lnbits/wallets/alby.py
Labels: wallets

#2089 pass custom extra on payment out
  lnbits/core/views/api.py
Labels: bug, feature request

#2107 docs: small cleanup
  .env.example
  README.md
  docs/devs/extensions.md
  docs/guide/faq.md
  docs/guide/wallets.md
Labels: documentation

#2121 feat: manage extensions navbar
  lnbits/static/bundle.min.js
  lnbits/static/i18n/br.js
  lnbits/static/i18n/cn.js
  lnbits/static/i18n/cs.js
  lnbits/static/i18n/de.js
  lnbits/static/i18n/en.js
  lnbits/static/i18n/es.js
  lnbits/static/i18n/fr.js
  lnbits/static/i18n/it.js
  lnbits/static/i18n/jp.js
  lnbits/static/i18n/kr.js
  lnbits/static/i18n/nl.js
  lnbits/static/i18n/pi.js
  lnbits/static/i18n/pl.js
  lnbits/static/i18n/pt.js
  lnbits/static/i18n/sk.js
  lnbits/static/i18n/we.js
  lnbits/static/js/components.js
  lnbits/static/js/service-worker.js
  lnbits/static/vendor.json
  lnbits/templates/base.html
  package.json
Labels: frontend, javascript

#2117 feat: add libwally for liquid support
  flake.nix
  poetry.lock
  pyproject.toml
Labels: dependencies, extension

#2126 feat: workflow to check bundle files
  .github/workflows/lint.yml
  .github/workflows/make.yml
  .gitignore
  Makefile
Labels: ci

#2100 set User-Agent when accessing external resources
  lnbits/core/services.py
  lnbits/core/tasks.py
  lnbits/core/views/api.py
  lnbits/core/views/node_api.py
  lnbits/extension_manager.py
  lnbits/settings.py
  lnbits/utils/exchange_rates.py
  lnbits/wallets/alby.py
  lnbits/wallets/corelightningrest.py
  lnbits/wallets/eclair.py
  lnbits/wallets/lnbits.py
  lnbits/wallets/lndrest.py
  lnbits/wallets/lnpay.py
  lnbits/wallets/lntips.py
  lnbits/wallets/opennode.py
  lnbits/wallets/spark.py
Labels: networking

#2130 fix issue with displaying languages
  lnbits/core/templates/core/extensions.html
  lnbits/core/templates/core/wallet.html
  lnbits/templates/base.html
Labels: bug
