Repository lnbits/lnbits, pull requests merged in 2024-03, with the labels that each got.

#2331 bug: Fix regression. Admin-users and allowed-users can now be removed through the web interface
  lnbits/core/templates/admin/_tab_users.html
Labels: bug

#2346 hotfix: initial currency conversion on balance
  lnbits/static/js/wallet.js
Labels: bug

#2349 bug: When "expiry" is null, do not display "expiry" in payment details
  lnbits/static/bundle.min.js
  lnbits/static/js/components.js
Labels: bug

#2341 feat: complete use of `LNBITS_EXTENSIONS_DEACTIVATE_ALL`
  lnbits/app.py
  lnbits/core/templates/admin/_tab_server.html
  lnbits/helpers.py
  lnbits/settings.py
  lnbits/static/bundle.min.js
  lnbits/static/js/components.js
  lnbits/templates/base.html
Labels: enhancement

#2364 chore: update to node 20.x on workflows
  .github/actions/prepare/action.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/jmeter.yml
  .github/workflows/make.yml
  .github/workflows/regtest.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: code health

#2365 bug: releasing docker image had invalid credentials
  .github/workflows/docker.yml
  .github/workflows/release.yml
Labels: bug

#2366 ci: run jmeter only if linting passes to save resources
  .github/workflows/ci.yml
  .github/workflows/jmeter.yml
Labels: ci

#2372 bug: frontend some v-text missing
  lnbits/core/templates/admin/_tab_server.html
  lnbits/core/templates/admin/_tab_users.html
Labels: bug

#2374 test: run jmeter test from `lnbits-extensions` repo
  .github/workflows/jmeter.yml
  integration/extensions-enable-all.jmx
  integration/fragments/init-account.jmx
  integration/fragments/init-server.jmx
  integration/lnurl.jmx
  integration/tpos.jmx
  integration/watchonly-satspay-tipjar.jmx
Labels: testing, code health

#2368 test: remove warnings for `TemplateResponse`
  lnbits/app.py
  lnbits/core/views/generic.py
  lnbits/middleware.py
Labels: testing, code health
