Repository lnbits/lnbits, pull requests merged in 2024-09, with the labels that each got.

#2619 chore: update pyproject dependencies
  flake.lock
  flake.nix
  lnbits/core/views/generic.py
  poetry.lock
  pyproject.toml
  tests/wallets/helpers.py
  tools/i18n-ai-tool.py
Labels: dependencies

#2665 fix: regeression on index.html
  lnbits/static/js/wallet.js
Labels: bug

#2618 Add detailed CSV export option
  lnbits/static/bundle.min.js
  lnbits/static/js/base.js
  lnbits/static/js/components/payment-list.js
Labels: feature request

#2678 Check for theme params on the URL
  lnbits/static/bundle.min.js
  lnbits/static/js/account.js
  lnbits/static/js/base.js
Labels: enhancement, themes, feature request
