Repository lnbits/lnbits, pull requests merged in 2024-04, with the labels that each got.

#2380 chore: adhere to ruff's `A`
  lnbits/commands.py
  lnbits/db.py
  pyproject.toml
  tests/core/views/test_node_api.py
  tools/i18n-check.py
Labels: code health

#2379 chore: adhere to ruff's `C`
  lnbits/core/views/extension_api.py
  lnbits/core/views/generic.py
  lnbits/core/views/payment_api.py
  lnbits/middleware.py
  lnbits/nodes/lndrest.py
  lnbits/server.py
  lnbits/wallets/fake.py
  lnbits/wallets/lndrest.py
  pyproject.toml
  tools/conv.py
Labels: code health

#2294 refactor: use new fastapi lifespan instead of startup/shutdown events
  flake.nix
  lnbits/app.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
Labels: code health

#2363 test: add unit tests for wallets (funding sources)
  .gitignore
  lnbits/wallets/base.py
  lnbits/wallets/corelightningrest.py
  lnbits/wallets/lndrest.py
  poetry.lock
  pyproject.toml
  tests/helpers.py
  tests/wallets/fixtures.json
  tests/wallets/test_rest_wallets.py
Labels: core, code health

#2377 chore: adhere to ruff's "N" rules
  .github/workflows/ci.yml
  lnbits/app.py
  lnbits/core/models.py
  lnbits/core/services.py
  lnbits/core/tasks.py
  lnbits/core/views/auth_api.py
  lnbits/core/views/generic.py
  lnbits/core/views/node_api.py
  lnbits/core/views/payment_api.py
  lnbits/core/views/websocket_api.py
  lnbits/db.py
  lnbits/decorators.py
  lnbits/settings.py
  lnbits/tasks.py
  lnbits/wallets/__init__.py
  lnbits/wallets/base.py
  lnbits/wallets/corelightning.py
  lnbits/wallets/corelightningrest.py
  lnbits/wallets/eclair.py
  lnbits/wallets/lndrest.py
  lnbits/wallets/opennode.py
  lnbits/wallets/zbd.py
  pyproject.toml
  tests/conftest.py
  tests/core/views/test_api.py
  tests/core/views/test_node_api.py
  tests/helpers.py
  tools/conv.py
Labels: code health

#2378 chore: adhere to ruff's `UP`
  lnbits/commands.py
  lnbits/db.py
  lnbits/middleware.py
  lnbits/nodes/base.py
  lnbits/nodes/cln.py
  lnbits/nodes/lndrest.py
  lnbits/settings.py
  lnbits/wallets/base.py
  lnbits/wallets/fake.py
  pyproject.toml
  tools/i18n-ai-tool.py
  tools/i18n-check.py
Labels: code health

#1628 FEAT: add PYPI python package release workflow on tag
  .dockerignore
  .github/workflows/release.yml
  .gitignore
  pyproject.toml
Labels: enhancement, deployment
